version: "3.9"

services:
  auth-service-db:
    image: mysql:latest
    container_name: auth-service-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RANDOM_ROOT_PASSWORD: false
    volumes:
      - auth-db-data:/var/lib/mysql1/data
    ports:
      - "3307:3306"
    networks:
      - internal
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - patient-db-data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
    networks:
      - internal
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: ${KAFKA_CFG_NODE_ID}
      KAFKA_PROCESS_ROLES: ${KAFKA_CFG_PROCESS_ROLES}
      KAFKA_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CFG_CONTROLLER_LISTENER_NAMES}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - internal
  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build: api-gateway
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
    networks:
      - internal
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build: auth-service
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME_MYSQL}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD_MYSQL}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_MYSQL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO_MYSQL}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE_MYSQL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      auth-service-db:
        condition: service_completed_successfully
    networks:
      - internal
  patient-service:
    image: patient-service:latest
    container_name: patient-service
    build: patient-service
    environment:
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
      BILLING_SERVICE_ADDRESS: ${BILLING_SERVICE_ADDRESS}
      BILLING_SERVICE_GRPC_PORT: ${BILLING_SERVICE_PORT}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - patient-service-db
      - api-gateway
    networks:
      - internal
  billing-service:
    image: billing-service:latest
    container_name: billing-service
    build: billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
    depends_on:
      - patient-service-db
      - kafka
    networks:
      - internal
  analytics-service:
    image: analytics-service:latest
    container_name: analytics-service
    build: analytics-service
    ports:
      - "4002:4002"
    environment:
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_SQL_INIT_MODE: ${SPRING_SQL_INIT_MODE}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      patient-service-db:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - internal
    restart: unless-stopped
volumes:
  auth-db-data:
  patient-db-data:
  kafka-data:
networks:
  internal:
    driver: bridge